[package]
name = "notion-to-markdown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_variant = "0.1.1"
notion = { git = "https://github.com/bram-dingelstad/notion-client-rs.git", package = "notion-client" }
